# Generated by Django 5.2.5 on 2025-09-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Modellar',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shablonNomi', models.CharField(blank=True, max_length=255, null=True)),
                ('rasm1', models.FileField(blank=True, null=True, upload_to='cars')),
                ('rasm2', models.FileField(blank=True, null=True, upload_to='cars')),
                ('rasm3', models.FileField(blank=True, null=True, upload_to='cars')),
                ('rasm4', models.FileField(blank=True, null=True, upload_to='cars')),
                ('rasm5', models.FileField(blank=True, null=True, upload_to='cars')),
                ('rasm6', models.FileField(blank=True, null=True, upload_to='cars')),
                ('ustama', models.FloatField(default=0)),
                ('UTCdanKeyingiNarx', models.FloatField(default=0)),
                ('GMC', models.FloatField(default=0)),
                ('UTCdanKeyingiBozorBahosi', models.FloatField(default=0)),
                ('natijaviySummaYozuvda', models.CharField(blank=True, max_length=255, null=True)),
                ('umumiyUTC', models.FloatField(default=0)),
                ('boyoqlashUTC', models.FloatField(default=0)),
                ('sumTamir2', models.FloatField(default=0)),
                ('sumTamir3', models.FloatField(default=0)),
                ('UTCAlmashtirish', models.FloatField(default=0)),
                ('almashtirishGeometrikegrilik', models.FloatField(default=0)),
                ('HJY', models.CharField(blank=True, max_length=50, null=True)),
                ('FY', models.CharField(blank=True, max_length=50, null=True)),
                ('YY', models.CharField(blank=True, max_length=50, null=True)),
                ('materiallar', models.JSONField(blank=True, null=True)),
                ('almashadiganDetallar', models.JSONField(blank=True, null=True)),
                ('umumiyTamir', models.FloatField(default=0)),
                ('tableTamirYechiladigan', models.JSONField(blank=True, null=True)),
                ('tableTamirYechilmaydigan', models.JSONField(blank=True, null=True)),
                ('tableIchki', models.JSONField(blank=True, null=True)),
                ('tableKuzov', models.JSONField(blank=True, null=True)),
                ('davlatRaqami', models.CharField(blank=True, max_length=20, null=True)),
                ('dvigatelRaqami', models.CharField(blank=True, max_length=50, null=True)),
                ('egasiningIsmi', models.CharField(blank=True, max_length=255, null=True)),
                ('expert', models.CharField(blank=True, max_length=255, null=True)),
                ('fotoaparatModeli', models.CharField(blank=True, max_length=255, null=True)),
                ('kuzovTuri', models.CharField(blank=True, max_length=255, null=True)),
                ('kMC', models.CharField(blank=True, max_length=50, null=True)),
                ('kMT', models.CharField(blank=True, max_length=50, null=True)),
                ('kuzovRaqami', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('rangi', models.CharField(blank=True, max_length=50, null=True)),
                ('uzatmalarQutisi', models.CharField(blank=True, max_length=50, null=True)),
                ('xulosaRaqami', models.CharField(blank=True, max_length=50, null=True)),
                ('xulosaSanasi', models.CharField(blank=True, null=True)),
                ('arizaSanasi', models.CharField(blank=True, null=True)),
                ('texpassportBerilganJoy', models.CharField(blank=True, max_length=255, null=True)),
                ('hozirgiYil', models.IntegerField(default=0)),
                ('arizaTushganKun', models.CharField(blank=True, null=True)),
                ('ishlabChiqarilganYil', models.IntegerField(default=0)),
                ('odometrKorsatkichi', models.IntegerField(default=0)),
                ('odometrNorma', models.IntegerField(default=0)),
                ('ishlabChiqarishdanToxtaganYil', models.IntegerField(default=0)),
                ('savdolashishcoefficienti', models.FloatField(default=0)),
                ('ishlabChiqarish', models.BooleanField(default=False)),
                ('odometrSozmi', models.BooleanField(default=False)),
                ('texpassportBerilganmi', models.BooleanField(default=False)),
                ('texpasportBerilganligi', models.FloatField(default=0)),
                ('chiqishToxtaganYil', models.IntegerField(default=0)),
                ('haqiqiyHizmatMuddati', models.IntegerField(default=0)),
                ('tanlanganJismoniyEskirish', models.FloatField(default=0)),
                ('jismoniyEskirishdanKeyingiSumma', models.FloatField(default=0)),
                ('analog1OdometrKorsatkichi', models.IntegerField(default=0)),
                ('analog2OdometrKorsatkichi', models.IntegerField(default=0)),
                ('analog3OdometrKorsatkichi', models.IntegerField(default=0)),
                ('analogNarxi1', models.FloatField(default=0)),
                ('analogNarxi2', models.FloatField(default=0)),
                ('analogNarxi3', models.FloatField(default=0)),
                ('boyoqlashVaqti', models.FloatField(default=0)),
                ('silliqlashVaqti', models.FloatField(default=0)),
                ('soatigaTolanadiganIshHaqqi', models.FloatField(default=0)),
                ('umumiyUstaHaqqi', models.FloatField(default=0)),
                ('yangisiningNarxi', models.FloatField(default=0)),
                ('ortachaNarx', models.FloatField(default=0)),
                ('jismoniyEskirish', models.FloatField(default=0)),
                ('bozorBahosi', models.FloatField(default=0)),
                ('umumiyNarxExtiyotQisimlar', models.FloatField(default=0)),
                ('jismoniyEskirishdanKeyingiNarx', models.FloatField(default=0)),
                ('umumiyNarxMateriallar', models.FloatField(default=0)),
                ('natijaviySumma', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Expertlar',
            },
        ),
        migrations.CreateModel(
            name='IchkiDetallarYechibOrnatish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='IchkiDetallar/')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ichki Detallar Yechib Ornatish',
                'verbose_name_plural': 'Ichki Detallar Yechib Ornatishlar',
            },
        ),
        migrations.CreateModel(
            name='Kuzov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kuzov',
                'verbose_name_plural': 'Kuzovlar',
            },
        ),
        migrations.CreateModel(
            name='KuzovGeometrikMurakkablik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kuzov Geometrik Murakkablik',
                'verbose_name_plural': 'Kuzovlar Geometrik Murakkablik',
            },
        ),
        migrations.CreateModel(
            name='KuzovYechibOrnatish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='kuzov/')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kuzov Yechib Ornatish',
                'verbose_name_plural': 'Kuzov Yechib Ornatishlar',
            },
        ),
        migrations.CreateModel(
            name='Materiallar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('olchov_birligi', models.CharField(max_length=20)),
                ('miqdor', models.FloatField(default=1)),
                ('narxi', models.FloatField()),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
            },
        ),
        migrations.CreateModel(
            name='Shablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='shablon')),
            ],
        ),
        migrations.CreateModel(
            name='TamirlashDarajasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField()),
            ],
            options={
                'verbose_name': 'Tamirlash Darajasi',
                'verbose_name_plural': 'Tamirlash Darajalari',
            },
        ),
        migrations.CreateModel(
            name='TanlanganDetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuzov_ids', models.JSONField(blank=True, default=list)),
                ('ichki_ids', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='YechiladiganDetallarTamirlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Yechiladigan Detallar Tamirlash',
                'verbose_name_plural': 'Yechiladigan Detallar Tamirlashlar',
            },
        ),
        migrations.CreateModel(
            name='YechilmaydiganDetallarTamirlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Yechilmaydigan Detallar Tamirlash',
                'verbose_name_plural': 'Yechilmaydigan Detallar Tamirlashlar',
            },
        ),
        migrations.CreateModel(
            name='KuzovTuriYemirilish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kuzov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KuzovTuriYemirilish', to='form.kuzov')),
            ],
            options={
                'verbose_name': 'Kuzov Turi Yemirilish',
                'verbose_name_plural': 'Kuzov Turi Yemirilish',
            },
        ),
        migrations.CreateModel(
            name='AlmashtiriladiganUTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.FloatField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.kuzovyechibornatish')),
            ],
            options={
                'verbose_name': 'Almashtirish UTC jadvali',
                'verbose_name_plural': 'Almashtirish UTC jadvali',
            },
        ),
        migrations.CreateModel(
            name='IchkiDetailCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IchkiDetalcoefficients', to='form.carmodel')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IchkiDetalcoefficients', to='form.ichkidetallaryechibornatish')),
            ],
            options={
                'verbose_name': 'Ichki Detail Coefficient',
                'verbose_name_plural': 'Ichki Detail Coefficients',
                'unique_together': {('car_model', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='KuzovGeometrikMurakkablikCoefficienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KuzovGeometrikMurakkablikCoefficienti', to='form.carmodel')),
                ('geometrik_murakkablik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KuzovGeometrikMurakkablikCoefficienti', to='form.kuzovgeometrikmurakkablik')),
            ],
            options={
                'verbose_name': 'Kuzovlar Geometrik Murakkablik  Coeficienti',
                'verbose_name_plural': 'Kuzovlar Geometrik Murakkablik Coeficienti',
                'unique_together': {('car_model', 'geometrik_murakkablik')},
            },
        ),
        migrations.CreateModel(
            name='KuzovDetailCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kuzovcoefficients', to='form.carmodel')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kuzovcoefficients', to='form.kuzovyechibornatish')),
            ],
            options={
                'verbose_name': 'Kuzov Detail Coefficient',
                'verbose_name_plural': 'Kuzov Detail Coefficients',
                'unique_together': {('car_model', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='TamirlashYechiladiganUTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tamir_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TamirlashYechiladiganUTC', to='form.tamirlashdarajasi')),
                ('detal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TamirlashYechiladiganUTC', to='form.yechiladigandetallartamirlash')),
            ],
            options={
                'verbose_name': 'Tamirlash UTC (Yechiladigan)',
                'verbose_name_plural': 'Tamirlash UTC (Yechiladigan)',
                'unique_together': {('detal', 'tamir_turi')},
            },
        ),
        migrations.CreateModel(
            name='TamirlashVaqtiYechiladigan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.FloatField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.carmodel')),
                ('daraja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.tamirlashdarajasi')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.yechiladigandetallartamirlash')),
            ],
            options={
                'verbose_name': 'Tamirlash Vaqti Yechiladigan',
                'verbose_name_plural': 'Tamirlash Vaqti Yechiladiganlar',
                'unique_together': {('car_model', 'detail', 'daraja')},
            },
        ),
        migrations.CreateModel(
            name='SilliqlashVaqtiYechiladiganlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.FloatField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.carmodel')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.yechiladigandetallartamirlash')),
            ],
            options={
                'verbose_name': 'Silliqlash Vaqti Yechiladiganlar',
                'verbose_name_plural': 'Silliqlash Vaqti Yechiladiganlar',
                'unique_together': {('car_model', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='BoyoqlashVaqtiYechiladiganlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.FloatField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.carmodel')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.yechiladigandetallartamirlash')),
            ],
            options={
                'verbose_name': 'Boyoqlash Vaqti Yechiladiganlar',
                'verbose_name_plural': 'Boyoqlash Vaqti Yechiladiganlar',
                'unique_together': {('car_model', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='TamirlashYechilmaydiganUTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tamir_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TamirlashYechilmaydiganUTC', to='form.tamirlashdarajasi')),
                ('detal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TamirlashYechilmaydiganUTC', to='form.yechilmaydigandetallartamirlash')),
            ],
            options={
                'verbose_name': 'Tamirlash UTC (Yechilmaydigan)',
                'verbose_name_plural': 'Tamirlash UTC (Yechilmaydigan)',
                'unique_together': {('detal', 'tamir_turi')},
            },
        ),
        migrations.CreateModel(
            name='TamirlashVaqtiYechilmaydigan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.FloatField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.carmodel')),
                ('daraja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.tamirlashdarajasi')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.yechilmaydigandetallartamirlash')),
            ],
            options={
                'verbose_name': 'Tamirlash Vaqti Yechilmaydigan',
                'verbose_name_plural': 'Tamirlash Vaqti Yechilmaydiganlar',
                'unique_together': {('car_model', 'detail', 'daraja')},
            },
        ),
        migrations.CreateModel(
            name='SilliqlashVaqtiYechilmaydiganlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.FloatField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.carmodel')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.yechilmaydigandetallartamirlash')),
            ],
            options={
                'verbose_name': ' Silliqlash Vaqti Yechilmaydiganlar',
                'verbose_name_plural': ' Silliqlash Vaqti Yechilmaydiganlar',
                'unique_together': {('car_model', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='BoyoqlashVaqtiYechilmaydiganlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.FloatField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.carmodel')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.yechilmaydigandetallartamirlash')),
            ],
            options={
                'verbose_name': 'Boyoqlash Vaqti Yechilmaydiganlar',
                'verbose_name_plural': 'Boyoqlash Vaqti Yechilmaydiganlar',
                'unique_together': {('car_model', 'detail')},
            },
        ),
    ]
