# Generated by Django 5.2.5 on 2025-09-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Carss',
        ),
    ]
