# Generated by Django 5.2.5 on 2025-09-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamirlashdarajasi',
            name='level',
            field=models.CharField(max_length=100),
        ),
    ]
