# Generated by Django 5.2.5 on 2025-09-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rename_cars_carss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carss',
            new_name='Cars',
        ),
    ]
