# Generated by Django 5.2.5 on 2025-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_carss_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='shablonNomi',
            field=models.FloatField(default=0),
        ),
    ]
