# Generated by Django 5.2.5 on 2025-09-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_cars_shablonnomi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='GMC',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='UTCAlmashtirish',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='UTCdanKeyingiNarx',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='almashtirishGeometrikegrilik',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='arizaSanasi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='arizaTushganKun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='boyoqlashUTC',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='ishlabChiqarish',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='jismoniyEskirishdanKeyingiSumma',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='odometrSozmi',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='savdolashishcoefficienti',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='shablonNomi',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='sumTamir2',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='sumTamir3',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='tanlanganJismoniyEskirish',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='texpasportBerilganligi',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='texpassportBerilganmi',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='umumiyTamir',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cars',
            name='xulosaSanasi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
